# Generated by Django 5.2 on 2025-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country_customuser_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_number',
            field=models.PositiveIntegerField(blank=True, help_text='Selected avatar image number', null=True),
        ),
    ]
