# Generated by Django 5.2 on 2025-04-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_delete_orderprofile'),
        ('home', '0002_alter_plan_options_remove_plan_contact_cta_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.plan'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
