# Generated by Django 5.2 on 2025-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('features', models.TextField(help_text='Separate features with a newline')),
                ('perfect_for', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=100)),
                ('cta_label', models.CharField(default='Pay Now', max_length=100)),
                ('contact_cta_label', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = higher display priority')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
