# Generated by Django 5.2 on 2025-04-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_plan_options_remove_plan_contact_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='button_class',
            field=models.CharField(blank=True, help_text='Button CSS class for styling', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome class', max_length=50),
        ),
    ]
