# Generated by Django 5.2 on 2025-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_plan_button_class_plan_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='icon_color_class',
            field=models.CharField(blank=True, help_text='CSS class for icon color', max_length=50),
        ),
    ]
