# Generated by Django 5.2 on 2025-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_plan_icon_color_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='button_class',
            field=models.CharField(blank=True, help_text="CSS class for styling the plan's button", max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(help_text='List of features separated by newlines'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome icon class used for the plan icon', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icon_color_class',
            field=models.CharField(blank=True, help_text='CSS class for controlling the icon color', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='long_description',
            field=models.TextField(help_text='Detailed description shown on the plan detail page'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly subscription price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='perfect_for',
            field=models.TextField(blank=True, help_text='Optional field describing ideal users or businesses', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], help_text='Type identifier used for internal logic and URL filtering', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='setup_cost',
            field=models.DecimalField(decimal_places=2, help_text='One-time setup cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='short_description',
            field=models.CharField(help_text='Brief description shown on pricing cards', max_length=255),
        ),
    ]
