# Generated by Django 5.2 on 2025-04-22 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_category_stretch_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=10)),
                ('chest', models.DecimalField(decimal_places=1, max_digits=5)),
                ('stretch_factor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_fits', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'size_label')},
            },
        ),
    ]
