# Generated by Django 5.2 on 2025-05-04 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_product_created_at_and_more'),
        ('sizemeapp', '0002_remove_garmentfit_stretch_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmentfit',
            options={'verbose_name': 'Garment Fit', 'verbose_name_plural': 'Garment Fits'},
        ),
        migrations.AlterField(
            model_name='garmentfit',
            name='chest',
            field=models.DecimalField(decimal_places=1, help_text='Chest width in centimeters for this size', max_digits=5),
        ),
        migrations.AlterField(
            model_name='garmentfit',
            name='product',
            field=models.ForeignKey(help_text='The product this size belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='size_fits', to='products.product'),
        ),
        migrations.AlterField(
            model_name='garmentfit',
            name='size_label',
            field=models.CharField(help_text='Label for the size, e.g. XS, S, M, L, XL', max_length=10),
        ),
    ]
