# Generated by Django 5.2 on 2025-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stretch_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Used internally to adjust fit recommendations', max_digits=4),
        ),
    ]
