# Generated by Django 5.2 on 2025-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_stretch_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stretch_factor',
        ),
        migrations.AddField(
            model_name='category',
            name='loose_factor',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Stretch factor for loose fit', max_digits=4),
        ),
        migrations.AddField(
            model_name='category',
            name='regular_factor',
            field=models.DecimalField(decimal_places=2, default=1.1, help_text='Stretch factor for regular fit', max_digits=4),
        ),
        migrations.AddField(
            model_name='category',
            name='slim_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Stretch factor for slim fit', max_digits=4),
        ),
    ]
